"""init user model is verified

Revision ID: 41dc194a0fce
Revises: a119fd13923b
Create Date: 2024-02-01 16:04:55.251763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41dc194a0fce'
down_revision: Union[str, None] = 'a119fd13923b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_super_user', sa.Boolean(), nullable=True))
    op.drop_constraint('user_user_name_key', 'user', type_='unique')
    op.drop_column('user', 'super_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('super_user', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_user_name_key', 'user', ['user_name'])
    op.drop_column('user', 'is_super_user')
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
